version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: nnpia
      POSTGRES_PASSWORD: nnpia
    ports:
      - 5433:5432