server:
  port: 9000
  servlet:
    context-path: /api/v1
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookdb
    username: nnpia
    password: nnpia
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

jwt:
  secret: topsecretstringthatnooneshouldknow

